spring:
  application:
    name: eureka-server

server:
  port: 30180

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false